### ISSUE TITLE
Are there any third party plugins available ?

### ISSUE THREAD

**Issue by kishoremadina** [labsai/EDDI#50]
To integrate with third party systems like SMTP do we have any plugins? Do we have more examples for different use cases ?

**Comment by ginccc** [comment]
Hi kishoremadina, 
thank you for you question. No, there is no SMTP plugin available right now; there used to be one but we removed it since it wasn't tested well enough and we wanted to provide only stable and tested plugins.
It is fairly simple though to develop one and integrate it easily as LifecycleTask to make it configurable via the API. Feel free to implement it and make a pull request. I can assist/guide you through the steps you will have to take in order to get there..
ad examples) I have many more examples on what can be done, but haven't found the time yet to put them to structure into the docs. We are currently working heavily on new features for the upcoming version 4.1 (e.g. quick-replies, context-information, templating, fb-messenger integration, ...), so I am afraid, the examples will have to wait a bit. Nonetheless, they are on my agenda, as well as improving the overall documentation. I expect to find time for this within this month!
