### ISSUE TITLE
Issues with swagger.json file created from docker image

### ISSUE THREAD

**Issue by mjbedford** [labsai/EDDI#58]
Firstly thank you for all your efforts, this looks like a very interesting project.

I have downloaded and build the docker images and they have started successfully and I can view the swagger ui

I have a couple of challenges

Firstly the default request URL points to port 80 on what appears to be your own host, I have found the swagger config but its not linked to a mounted volume so it will not be persisted when restarting the docker image. Is there a way to change this so it does get persisted?

Secondly I have retrieved the swagger.json file from the running docker and tried to import it into my app dev tool and it has found that you are using definitions with objects with no properties, is this intentional as I am told that definitions of type object have to either ref a model or define properties.

Thanks M

**Comment by ginccc** [comment]
Hi! Thanks for your questions/feedback;

ad port 80) yes, that was a misconfigruation on our side; has been fixed two days ago and is reflected in the latest version (github master/docker hub:latest)
[just as a side note: output configuration has changed massively which has not been updated in the docs yet, so don't be surprised. nonetheless, you can see the new model in swagger-ui]

ad swagger.json) 
I am not sure if I understand you correctly; what type of properties are you missing? the rest interfaces refer to objects, which are defined at the very end of the swagger.json file.
This is also visible in the swagger-ui, and also works as expected (as the swagger-ui uses the swagger.json in order to make the requests)
If you can clarify you problem in more depth I'd be happy to assist you and certainly fix any bugs in case we encounter that this misbehavior is code related.

let me know..
Gregor
