### ISSUE TITLE
No bot output in conversation

### ISSUE THREAD

**Issue by kientt1001** [labsai/EDDI#73]
Dear team,
I followed the guidelines and successfully setup & create a chat bot.
For bot creation, I use sample Json in your document with generated Unique_Ids in Package & Bot.
But when I go http://localhost:7070/chat/My_Bot_ID I get chat form with empty content. No welcome message (as in test screen capture). Also there is NO output from from bot when I send Hi, hello, ...
I checked the http response and saw that the bot returns conversation steps with correct actions. But NO output. I checked the IDs carefully. Am I missing some steps here?
Thank you,

**Comment by ginccc** [comment]
I assume you are using the master branch? Documentation is not updated yet. master is reflecting a new version (4.1.0) which has some breaking changes, foremost in output config. 

In accordance to the docs, use version 4.0.2, then it will work.

However, since 4.1.0 is about to be released soon, it is not a bad idea to go for it, since it contains a lot of improvements. Checkout the config files in the integration tests and compare them to yours, those reflect the latest config versions: https://github.com/labsai/EDDI-integration-tests/tree/master/src/test/resources/tests/botengine

If you have any further questions, let me know.

**Comment by kientt1001** [comment]
Hi Ginccc,
Thank you for your answer. You're right. I test with the master branch. I'll try again with new settings you suggested. Thank you.

**Comment by ginccc** [comment]
docs are updated now: 
https://labsai.atlassian.net/wiki/spaces/EDDI/overview
https://labsai.atlassian.net/wiki/spaces/EDDI/pages/168410/Creating+a+Chatbot
More is coming in the next few days.. 
release of 4.1.0 approx in 1-2 weeks

**Comment by kientt1001** [comment]
Thank you for the update.
I can see more documents available now. Keep it up!
Best regards,
Kien

**Comment by ginccc** [comment]
yes, sir. Will do :)

Plan is to have all major parts documented before releasing 4.1.0. Stay tuned. ;-)

**Comment by kientt1001** [comment]
Hello gincc,
I wonder if I can create chat bot with languages other than English (such as Vietnamese, Korean, Japanese, ...)? If yes, what is the correct setting (in package, I guessed)?
I think you must be very busy with documentations when I see the list of modules. :)

**Comment by ginccc** [comment]
Hi kientt1001,
that is an interesting question; in theory I believe it should work with any language, since EDDI is only language depended at the parser level (then translates into a meta language = expressions) and then again at the output level - so the main flow of eddi configs wouldn't be affected by the choice of language you make. 
Furthermore, everything in EDDI is UTF-8, therefore I am quite confident that it should work with Asian languages as well.
But please, try it and let me know :-)
Ad parser) you will need to make separate dictionaries and separate outputsets for each language, I'd recommend doing separate bots/packages for each language - easier to maintain..
ad intent detection) can you elaborate a bit more on what you plan exactly?

documentation still needs some time, since we are quite busy in QAing as well as integration work with our Google Partnership on GCloud. But it is on our list ;-)

**Comment by kientt1001** [comment]
Hi ginccc,
It sounds like a great news for the Google partnership. 
I managed to make a chatbot with Korean with minor changes in allowed characters. I'm thinking of using regular expression instead of listing all chars. But it will be difficult for normal users to understand.

I want to build chatbot with intent detection, slots filling and smart help cards (like multiple choice, form, map,...) rendering as well. I'm still searching for a solution ... E.D.D.I may be a good starting point :)
Thank you,

**Comment by ginccc** [comment]
ad korean) sounds interesting; regex can be slow at times, so this should be made efficient. We can certainly consider putting a regex as a config option into the normalizer, so, if you want to make some changes here, feel free to make a pull request for it :-)

intent detection is something that eddi achieves with the semantic parser (although you have to feed all the information itself as it doesn't come with any pre configs)
slot filling you mean in the recognition or for templating?
smart cards as you call it can be currently solved with defining quick replies and rendering it specifically on the client side the way you need it

**Comment by kientt1001** [comment]
Slot filling is to get user defined attributes from conversation. I.e: 
{ class: pizza, size: [large, medium, small], base-plate: [thin, thick], ...}
Then the bot can ask and get the size and base-plate type from user.
Also, i'm waiting updates to behavior rule documents :)
Thank you for your suggestions and patiently answering my questions.

**Comment by ginccc** [comment]
i see. Well, this isn't there as a feature, yet. You could define manually quick replies for the moment, but I understand that this isn't ideal.
Would you mind creating a jira user story explaining in depth with some specific examples how you would like to have it? :-)

still owning some documentation, I know.. :-/ busy with conference and event talks at the moment. 
Nonetheless, 4.1.0 is scheduled for October 1st, by then I will make sure it is completed! 
Hope you can wait for it..
