### ISSUE TITLE
Is there any default out configuration?

### ISSUE THREAD

**Issue by dgks0n** [labsai/EDDI#79]
Gregor,
In some cases, the user input didn't match with any actions defined thus the bot replied nothing. 
Can EDDI allow configure default output for that case? The default output will be configured by the chatbot creator.

Thanks

**Comment by ginccc** [comment]
the way to solve this, is to define a behavior rule that will be successful if nothing else is, which will trigger a default action that in turn will trigger a default output.

The simplest way would be to define an empty behavior rule at the end of an behavior group without any conditions. this rule will be always successful.
To be a bit more specific, you can define this last rule in a group with a inputmatcher condition that is looking for "unknown(*)" expressions, or "unused(*)" in case you are expecting user inputs that you have defined in a dictionary but not using anywhere in your behavior rules. 
the third option (least preferable one) would be to define one behavior rule, that has multiple "dependency" conditions to all other available rules, so that this rule only succeeds if all other rules fail. 
Although possible, I don't recommend the third option. It is rather slow, hard to maintain and error prune.
Go for option 1 if it suits your use case, or option 2 otherwise.

**Comment by dgks0n** [comment]
Sorry, I'm confusing a little for the second option:

>>>The simplest way would be to define an empty behavior rule at the end of an behavior group >>>without any conditions. this rule will be always successful.
>>>To be a bit more specific, you can define this last rule in a group with a inputmatcher condition >>>that is looking for "unknown( * )" expressions, or "unused( * )" in case you are expecting user >>>inputs that you have defined in a dictionary but not using anywhere in your behavior rules.

I defined a phrase in the dictionary like this:

```
    {
      "phrase": "I don't understand",
      "exp": "unknown(*)"
    }
```

and new rule at the end of behavior group as below:

```
    {
          "name": "Unknown",
          "actions": [
            
          ],
          "children": [
            {
              "type": "inputmatcher",
              "values": {
                "expressions": "unknown(*)"
              }
            }
          ]
        }
```
But for this sentence, you said: `but not using anywhere in your behavior rules`. What does this sentence mean?

Can you explain more clearly? 
Thank you

**Comment by ginccc** [comment]
no, you don't have to define unknown in the dictionary, since the nlp parser will put unknown by default if it cannot match anything in a dictionary.
It can make sense to define phrases and words in the dictionary that are not used by you, in order to enhance the accuracy of the spelling corrections. in that case we you only place the words and phrases the nlp would put it as unused instead of unknown.

the rule as you put it is fine.

**Comment by dgks0n** [comment]
Thank you, Gregor. It works.

**Comment by ginccc** [comment]
great! Happy to be able to help :-)
