### ISSUE TITLE
Input Matcher does not support parsing regular expression

### ISSUE THREAD

**Issue by dgks0n** [labsai/EDDI#80]
Gregor, I'm considering to use EDDI to create new chatbot engine for a specific domain but as my understanding, the input matcher does not work with the regular expression. I have a lot of words or phrases that user can input but many are almost same. Thus, I think it's better if it's able to use the regular expression to define the phrase. For example:

```
{
    "phrase": "I would like to buy ${itemName}",
    "exp": "buy_item(${itemName})"
}
```

Is this possible with EDDI?

**Comment by ginccc** [comment]
Hi,
so, you are describing different issues here, so let's make this clear first before we talk about an actual solution..
1) Matching happens within the Parser, it is possible to create Custom Dictionaries in order to match all kind of things. Regex would be one option to match something. I have always tried to avoid this since it is rather hard to maintain over time and also is pretty slow compared to other matching strategies. 
But certainly it could be done. 
Another reason for matching only things that you are aware of is that if you are too open of matching all kind of "similar" things, you end up having a lot of false positives, which is really bad..

Can you give a few examples of what you would like to be matchable? 

2) the code example you gave are two different features IMO
2.1) matching of dynamic value within a phrase
here again I would like to ask you to give concrete examples so we can sort out a proper solution. If you would match anything after the "I would like to buy", than you would ran into the problem that users might use inappropriate words at this point and from a qualitative perspective you would only want to match things that you are actually be able to handle!  
2.2) using this matched value and place it dynamically into the expression
That is certainly an interesting idea and not so difficult to be implemented either..
Let's first discuss the questions I have raised and than find an overall satisfying solution!

btw. 4.1.0 has been released, will make an official statement soon and also complete the docs, but code is freezed and works very well in our usecases.. :-)

Gregor

**Comment by dgks0n** [comment]
I apologize for making you confused. Actually, I described two kinds of issues. The first issue is that it's able to use regex within the input parser. Let say I have a few sentences such as: "I would like to buy a pen", "I'd like to buy a book", "I want to buy a car", ...or something like that. Now, I don't want to define words or phrases for each sentence because it had too many. Thus, it's better to create new Custom Dictionaries or regex to match all kind of things that had same meaning.

The second is: matching of dynamic value within a phrase and use that matched value for next step. This is a sample:

```
A: I would like to buy a pen?
B (Robot): What kind of pen you want to buy?

Or

A: I would like to buy a watch?
B (Robot): What kind of watch and what's size needs?
```

**Comment by dgks0n** [comment]
@ginccc Can you give me a suggestion for this kind of expectation?

**Comment by ginccc** [comment]
Hi,

sorry for not following up sooner, lots of stuff to do..

*) Not sure how regex would help you in your case, since you want to simple match different unknown words, you could just match for the phrase "I would like to buy a" -> "item" , but than again you wouldn't be able to use this word any further.

So to sum up:
The way this feature could work properly would be to be able to match meaning within a phrase either by regex, expression (such as carModel(*)) or the '*' operator. Then, map this match similar to what you have suggested.
Another issue then is to be able to use this in the output. There is a templating available already, but it isn't linked to expression values yet. 

In order for this to work as you need it there are three tasks to be done:
1) dynamic matching within a phrase (/maybe even based on a word - as dictionary)
2) creating an expression with this matched value
3) making the expressions available in output templating

So, it is doable with some programming effort, that's the good news.
The not so good news is that this is not really on our agenda right now, so not sure when we would find time to do this....
Could you imaging developing this feature yourself (with guidance from me) ?

**Comment by dgks0n** [comment]
Yeap, you are correct. I think the issue could be done if three below tasks to be done:

1. dynamic matching within a phrase (/maybe even based on a word - as dictionary)
2. creating an expression with this matched value
3. making the expressions available in output templating

But for the first task, I don't have any idea for matching within a phrase by using the dictionary. Could you send me an example of how to define expression?

**Comment by ginccc** [comment]
expressions are just String that are recognized as Objects within eddi.. The originate from Prolog, which is a predicate oriented language from the past.

Example: food(pizza), shoes(size(5))
Within parenthesis you can define children that can have children themselves and those create a relation between them. 

To implement this into the Parser is a bit of a challenge maybe.. if would need to be possible to define semantic matches of syntactic ones, such as

This is a phrase that should match all kind of [exp: food(*)]
This is another phrase that should match all kind of [reg: [0-9a-zA-z]]

**Comment by dgks0n** [comment]
Thanks @ginccc for your answer, so for the below:
1. dynamic matching within a phrase (/maybe even based on a word - as dictionary)

is there a template available already but not linked, right? If not yet, is there any way to implement it with E.D.D.I?
