### ISSUE TITLE
What is the best way to get rules calling another REST API

### ISSUE THREAD

**Issue by ouaibsky** [labsai/EDDI#87]
Hi

My need is the following
* Define some input matcher
* Attach an REST endpoint to this input (with some context (security, history ...)
* send back to the conversation the output of the REST endpoint .

Idea is to reuse some internal rest api (developed in various language) that provide kind of "user interaction".

I'm discovering E.D.D.I and unfortunately not able to find doc on this at https://labsai.atlassian.net/wiki/display/EDDI/

I had a look into code, found Conversation callback but not sure it matches what I want

Any idea on how to implements this is welcome

Thx in advance.
Chris

**Comment by ginccc** [comment]
Hi there,

yes, indeed there is functionality available that is not covered in the docs yet.
One way is to use the LifecycleTask "callback", as you correctly identified:
The callback task plugin, which sends the entire conversation memory as json to another external rest service and receives back an update conversationMemory (such as data other services)  is used similar like the parser, behavior or output ("eddi://ai.labs.callback").
the config is callbackUri & timeoutInMillis
callbackUri should be a service that receives a json based on this model (https://github.com/labsai/EDDI/blob/master/conversationmemory-definition/src/main/java/ai/labs/memory/model/ConversationMemorySnapshot.java), alter it or populate it with all kinds of data and send the update conversationMemory back as response so eddi can merge it with its internal memory.

If you want to populate data dynamically in the output, there is another yet undocumented feature - templating! The LifecycleTask is called "eddi://ai.labs.templating" and would allow to populate data such as "Hello [[${userInfo.username}]]! Nice to meet you! :-)". Internally it uses the Framework "Thymeleaf".
In order to be able to use the object notations you would need to put context data into the conversation memory, such as:
```
{
  <...>
  "conversationSteps": [
    {
      "conversationStep": [
        {
          "key": "context:userInfo",
          "value": {
            "type": "object",
            "value": {
              "username": "Gregor"
            }
          }
        }
      ]
    }
  ]
}
```
OR hand it over with the input at the beginning such as: 

```
{"input":"user input here",
"context":
{"userInfo":{"type":"object","value":{"username":"Gregor"}}
}}
```

Hope that helps, sorry for the lack of documentation..

Gregor

**Comment by ginccc** [comment]
The integration tests is another place to look for how-things-work: https://github.com/labsai/EDDI-integration-tests

**Comment by ouaibsky** [comment]
Hi
Thx for the update.
I end-up with same conclusion about **eddi://ai.labs.callback**

What remains unclear to me is how and where to configure it: into behavior, output  ...whatever rules
If you could provide a snapshot I'l appreciate otherwise I'll have a look to integration test.

Chris.

**Comment by ginccc** [comment]
You configure it in the package, on the same level as parser, behavior or output. You probably want to have it after behavior and before output to be able to get the actions from the rules and populate data so you can fill the output.

**Comment by ginccc** [comment]
just realized that you originally asked for rules calling another rest-api...
There is no rule extension yet that makes a rest call.

Altough it would be quite easy to implement, sending the conversation memory and getting back a boolean....
