### ISSUE TITLE
4.1.0 version has compilation error.

### ISSUE THREAD

**Issue by khhwang838** [labsai/EDDI#88]
I'm trying to setup EDDI project on my eclipse and got a compilation error on line 249 of HistorizedResourceStoreTest.java file in configurationrepository-impl project. It says,

**The interface IResource cannot be implemented more than once with different arguments: IResourceStorage.IResource and IResourceStorage.IResource**

Any suggestions?

**Comment by ginccc** [comment]
Difficult to say; it is building just fine locally as well as in CI (check out: https://circleci.com/gh/labsai/EDDI/265)

What Java version do you use? 
Did your IDE maybe try to "optimize" the imports and ending up making a mistake here?

line 249 has IResourceStorage.IHistoryResource as an interface, so not sure why bugging..

We use intellij as our IDE, maybe you want to try it with this to see if the error persists. Otherwise it seems to be related to your IDE.

**Comment by khhwang838** [comment]
I'm using Eclipse Oxygen. 1a Release (4.7.1a) Build id: 20171005-1200 with jdk 1.8.0_151 on Windows 10. The reason why I got this error is that TestHistoryResource class extends TestResource which implements IResourceStorage.IResource and it also implements IResourceStorage.IHistoryResource which extends IResource. So, it seems like TestHistoryResource implements IResource twice by extending TestResource and implementing IHistoryResource. Since this file is for just testing, I can ignore the error but have no idea why you didn't get the error. Maybe different version of Java? Hmm..

**Comment by ginccc** [comment]
I am using the same version of java. haven't gotten this error.. as I said, maybe it is the IDE..
But yes, it is only for testing, so not severe..
